/**
 * TC: 
 * SC:
 * The gray code is a binary numeral system where two successive values differ in only one bit.
 * if i == 0 gray code = [0]
 * if i == 1 => add 1>>(n-1) to graycode generated by n-1 in reverse order.
 * @param {number} n 
 * @returns 
 */
function grayCode(n){
    if(n==0){
        const list = []
        list.push(0)
        return list
    }
    const arr = grayCode(n-1)
    for(let i= arr.length-1;i>=0;i--){
        arr.push(arr[i] | 1<<(n-1))
    }
    return arr   
}
console.log(grayCode(2))

//https://leetcode.com/problems/gray-code/description/